In [2]:
import pandas as pd




In [3]:
df=pd.read_csv('cars.csv')
df.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [4]:
pd.get_dummies(df,columns=['owner','fuel']) #one hit encoding usimg pandas
               #here we are not using multi collinearity  concept 


brand  km_driven  selling_price  owner_First Owner  \
0      Maruti     145500         450000               True   
1       Skoda     120000         370000              False   
2       Honda     140000         158000              False   
3     Hyundai     127000         225000               True   
4      Maruti     120000         130000               True   
...       ...        ...            ...                ...   
8123  Hyundai     110000         320000               True   
8124  Hyundai     119000         135000              False   
8125   Maruti     120000         382000               True   
8126     Tata      25000         290000               True   
8127     Tata      25000         290000               True   

      owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
0                          False               False                 False   
1                          False                True                 False   
2                          False               False                 False   
3                          False               False                 False   
4                          False               False                 False   
...                          ...                 ...                   ...   
8123                       False               False                 False   
8124                        True               False                 False   
8125                       False               False                 False   
8126                       False               False                 False   
8127                       False               False                 False   

      owner_Third Owner  fuel_CNG  fuel_Diesel  fuel_LPG  fuel_Petrol  
0                 False     False         True     False        False  
1                 False     False         True     False        False  
2                  True     False        False     False         True  
3                 False     False         True     False        False  
4                 False     False        False     False         True  
...                 ...       ...          ...       ...          ...  
8123              False     False        False     False         True  
8124              False     False         True     False        False  
8125              False     False         True     False        False  
8126              False     False         True     False        False  
8127              False     False         True     False        False  

[8128 rows x 12 columns]

In [6]:
pd.get_dummies(df,columns=['owner','fuel'],drop_first=True) # this is calles (n-1) encoding in ine hot encoding as 
#we have drop first column from both  fuel and owner

brand  km_driven  selling_price  owner_Fourth & Above Owner  \
0      Maruti     145500         450000                       False   
1       Skoda     120000         370000                       False   
2       Honda     140000         158000                       False   
3     Hyundai     127000         225000                       False   
4      Maruti     120000         130000                       False   
...       ...        ...            ...                         ...   
8123  Hyundai     110000         320000                       False   
8124  Hyundai     119000         135000                        True   
8125   Maruti     120000         382000                       False   
8126     Tata      25000         290000                       False   
8127     Tata      25000         290000                       False   

      owner_Second Owner  owner_Test Drive Car  owner_Third Owner  \
0                  False                 False              False   
1                   True                 False              False   
2                  False                 False               True   
3                  False                 False              False   
4                  False                 False              False   
...                  ...                   ...                ...   
8123               False                 False              False   
8124               False                 False              False   
8125               False                 False              False   
8126               False                 False              False   
8127               False                 False              False   

      fuel_Diesel  fuel_LPG  fuel_Petrol  
0            True     False        False  
1            True     False        False  
2           False     False         True  
3            True     False        False  
4           False     False         True  
...           ...       ...          ...  
8123        False     False         True  
8124         True     False        False  
8125         True     False        False  
8126         True     False        False  
8127         True     False        False  

[8128 rows x 10 columns]

In [21]:
#one hot encoding using Sklearn but not using column transformer
from sklearn.model_selection import train_test_split

In [22]:
# first split dataset in train test and split
X_train, X_test,Y_train,Y_test=train_test_split(df.iloc[:,:4],df.iloc[:,-1],test_size=0.2,random_state=42)

In [23]:
#import One hot Encoder
from sklearn.preprocessing import OneHotEncoder

In [26]:
ohe=OneHotEncoder()

In [30]:
X_train_new=ohe.fit_transform(X_train[['fuel','owner']]).toarray()

In [31]:
X_train_new

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [32]:
# now for further we take columns from X_train and add to X_train_new  using hstack

In [33]:
X_test_new=ohe.fit_transform(X_test[['fuel','owner']]).toarray()
X_test_new

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [46]:
import numpy as np

In [48]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Tata', 2560, 0.0, ..., 0.0, 0.0, 0.0],
       ['Honda', 80000, 0.0, ..., 1.0, 0.0, 0.0],
       ['Hyundai', 150000, 0.0, ..., 0.0, 0.0, 0.0],
       ...,
       ['Hyundai', 35000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 27000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 70000, 0.0, ..., 1.0, 0.0, 0.0]], dtype=object)

In [ ]:
#there are twi ways either we  perform one hot 
#encoding on column by splitting them from main or we can do so by column tranformer


#
One Hot Encoding with Column Transformer 

In [34]:
from sklearn.compose import ColumnTransformer

In [44]:
transformer=ColumnTransformer(transformers=[("trnf1",OneHotEncoder(sparse_output=False,drop='first'),['fuel','owner'])])

In [45]:
transformer.fit_transform(X_train)

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.]])